package com.ing.zkflow.zinc.poet.generate.structure

import com.ing.zkflow.annotations.ZKP
import com.ing.zkflow.annotations.ZKPSurrogate
import com.ing.zkflow.common.serialization.KClassSerializerProvider
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.serializer
import net.corda.core.internal.writeText
import java.nio.file.Paths
import java.util.ServiceLoader

private val json = Json {
    encodeDefaults = true // otherwise `comment` is not serialized
    prettyPrint = true
    prettyPrintIndent = "  "
}

const val GENERATE_ZKP_STRUCTURE = "generateZkpStructure"

@Serializable
data class ZkpStructure(
    @SerialName("__comment__")
    val comment: String = "!!!DO NOT MODIFY!!! This file is generated by `$GENERATE_ZKP_STRUCTURE`. " +
        "This file contains a generated baseline of the serialization structure for all @${ZKP::class.simpleName} " +
        "and @${ZKPSurrogate::class.simpleName} classes to detect and prevent backwards incompatible changes.",
    val structure: List<ZkpStructureType>,
)

fun main() {
    val kClassSerializerProviders = ServiceLoader.load(KClassSerializerProvider::class.java)
    val structureTypes = kClassSerializerProviders
        .asSequence()
        .map { it.get().klass }
        .flatMap { ZkpStructureGenerator.generate(it.serializer().descriptor).toFlattenedClassStructure() }
        .distinct()
        .toList()
    val structure = ZkpStructure(
        structure = structureTypes
    )
    val jsonString = json.encodeToString(ZkpStructure.serializer(), structure)
    Paths.get("src/main/zkp/structure.json").writeText(jsonString)
}
