trigger:
  branches:
    include:
      - master
        #      - feature/* # Already covered by branch validation rules on master

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

steps:
  - task: Cache@2
    inputs:
      key: 'gradle | "$(Agent.OS)" | **/*.gradle.kts | **/gradle.properties'
      restoreKeys: |
        gradle | "$(Agent.OS)"
        gradle
      path: $(GRADLE_USER_HOME)
    displayName: Configure gradle caching

  # This should be amended to download from Azure artifacts once that is set up for the Zinc repo.
  #  - task: DownloadGitHubRelease@0
  #    displayName: 'Fetch Zinc from Github'
  #    inputs:
  #      connection: 'Github Public Repo Access'
  #      userRepository: 'ingzkp/zinc'
  #      defaultVersionType: 'latest'
  #      itemPattern: 'zinc-linux.tar.gz'
  #      downloadPath: '$(System.ArtifactsDirectory)'

  - task: Bash@3
    displayName: 'Install Zinc in PATH'
    inputs:
      targetType: 'inline'
      script: |
        mkdir $(Pipeline.Workspace)/
        tar xvzf $(Build.SourcesDirectory)/.ci/lib/zinc-linux.tar.gz --directory $(Pipeline.Workspace)
        echo "##vso[task.prependpath]$(Pipeline.Workspace)/zinc-linux/"

  - task: Bash@3
    displayName: 'Confirm Zinc in PATH'
    inputs:
      targetType: 'inline'
      script: |
        echo $PATH
        znc --version

  - task: Gradle@2
    displayName: 'ZKFlow build'
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx8192m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean cleanTest check test testReport jacocoRootReport'
      # options: '--stacktrace --info --build-cache'
      options: '--no-build-cache --rerun-tasks --no-daemon --no-parallel --stacktrace --info '
    env:
      GITHUB_USERNAME: $(github.username)
      GITHUB_TOKEN: $(github.token)

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: '$(Build.SourcesDirectory)/build/reports/jacoco/aggregate/jacocoTestReport.xml'
      reportDirectory: '$(Build.SourcesDirectory)/build/reports/jacoco/aggregate/html'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish detekt report'
    inputs:
      targetPath: '$(Build.SourcesDirectory)/build/reports/detekt'
      artifact: 'Detekt report'
      publishLocation: 'pipeline'

  - task: Gradle@2
    displayName: 'ZKDapp Tester build'
    inputs:
      workingDirectory: 'sample-zkdapp'
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx8192m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean cleanTest build'
      # options: '--stacktrace --info --build-cache'
      options: '--no-build-cache --rerun-tasks --no-daemon --no-parallel --stacktrace --info '
    env:
      GITHUB_USERNAME: $(github.username)
      GITHUB_TOKEN: $(github.token)

  - script: |
      # stop the Gradle daemon to ensure no files are left open (impacting the save cache operation later)
      ./gradlew --stop
    displayName: Stop Gradle daemon
    condition: always()
