name: ZK Notary SDK CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8.0.x (FX)
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.x
          java-package: jdk+fx

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-1
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew assemble --build-cache --stacktrace --parallel
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check:
    runs-on: ubuntu-latest
    needs: assemble

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8.0.x (FX)
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.x
          java-package: jdk+fx

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-1
          restore-keys: ${{ runner.os }}-gradle

      - name: Fetch Zinc ING Fork
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "ingzkp/zinc"
          version: "latest"
          file: "zinc-linux.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Zinc ING Fork to path
        run: |
          tar xvzf zinc-linux.tar.gz
          echo "::add-path::$GITHUB_WORKSPACE/zinc-linux/"
          pwd
          ls -l

      - name: Build with Gradle
        run: |
          echo $PATH
          ./gradlew check --build-cache --stacktrace --parallel
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
