name: PRs and merges to master

env:
  ZINC_VERSION: "v0.1.5-ING-8"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8.0.232
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.232
          java-package: jdk

      # Build cache
      - name: Cache Gradle Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}-${{ hashFiles('**/gradle.properties') }}
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Fetch Zinc ING Fork
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "ingzkp/zinc"
          version: "tags/${{ env.ZINC_VERSION }}"
          file: "zinc-linux.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Zinc ING Fork and add to $PATH
        run: |
          tar xvzf zinc-linux.tar.gz
          echo "$GITHUB_WORKSPACE/zinc-linux/" >> $GITHUB_PATH

      - name: Build with Gradle
        run: ./gradlew check test slowTest testReport --stacktrace --info --build-cache
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: zkdapp-tester - Init new circuit and Process Zinc sources with Gradle
        run: ../gradlew processZincSources createZincDirectoriesForInputCommand --command test-command  --stacktrace --info --build-cache
        working-directory: zkdapp-tester
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: zkdapp-tester - Compile test-command circuit with Zargo
        run: zargo build -v
        working-directory: zkdapp-tester/build/zinc/test-command
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ivno - Build with Gradle
        run: ../gradlew build --stacktrace --info --build-cache
        working-directory: ivno
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Ivno - Compile deposit-request circuit with Zargo
#        run: zargo build -v
#        working-directory: ivno/ivno-collateral-token-contract/build/zinc/deposit-request
#        env:
#          GITHUB_USERNAME: ${{ github.actor }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JUnit test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Junit Test Report
          path: build/reports/tests/test

      - name: Upload detekt report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Detekt Report
          path: build/reports/detekt
