name: Publish artifacts on tag

on:
  push:
    tags:
      - 'release/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Git info
        id: git_info
        run: |
          echo ::set-output name=RELEASE_VERSION::${GITHUB_REF#refs/tags/release/}

      - name: Set up JDK 8.0.232
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.232
          java-package: jdk

      # Build cache
      - name: Cache Gradle Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}-${{ hashFiles('**/gradle.properties') }}
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}


      - name: Publish to GitHub Packages (should never fail)
        run: ./gradlew -Pversion=$GIT_RELEASE_VERSION publish --continue --build-cache --parallel
        env:
          GIT_RELEASE_VERSION: ${{ steps.git_info.outputs.RELEASE_VERSION }}
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
