name: Publish artifacts on tag

#env:
#  ZINC_VERSION: "v0.1.5-ING-4"

on:
  push:
    tags:
      - '*'

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8.0.232
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.232
          java-package: jdk

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-1
          restore-keys: ${{ runner.os }}-gradle

      - name: Fetch Zinc ING Fork
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "ingzkp/zinc"
          version: "tags/${{ env.ZINC_VERSION }}"
          file: "zinc-linux.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Zinc ING Fork and add to $PATH
        run: |
          tar xvzf zinc-linux.tar.gz
          echo "$GITHUB_WORKSPACE/zinc-linux/" >> $GITHUB_PATH

      - name: Build with Gradle
        run: ./gradlew assemble --build-cache --stacktrace --parallel
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: assemble

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8.0.232
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.232
          java-package: jdk

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-1
          restore-keys: ${{ runner.os }}-gradle

      - name: Publish to GitHub Packages (should never fail)
        run: ./gradlew publish --continue --build-cache --parallel
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
