name: Nightly build

env:
  ZINC_VERSION: "v0.1.5-ING-6"

on:
  schedule:
    # Run nightly at 04:00, so we don't use up our run hours too fast
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  all-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8.0.232
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.232
          java-package: jdk

      # Build cache
      - name: Cache Gradle Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}-${{ hashFiles('**/gradle.properties') }}
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Fetch Zinc ING Fork
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "ingzkp/zinc"
          version: "tags/${{ env.ZINC_VERSION }}"
          file: "zinc-linux.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Zinc ING Fork and add to $PATH
        run: |
          tar xvzf zinc-linux.tar.gz
          echo "$GITHUB_WORKSPACE/zinc-linux/" >> $GITHUB_PATH

      - name: Build with Gradle
        run: ./gradlew check dependencyCheckAggregate test slowTest nightlyTest testReportAll jacocoTestReport --build-cache --stacktrace --info
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Init new circuit and Process Zinc sources with Gradle
        run: ../gradlew processZincSources createZincDirectoriesForInputCommand --command test-command
        working-directory: zkdapp-tester
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile test-command circuit with Zargo
        run: zargo build -v
        working-directory: zkdapp-tester/build/zinc/test-command
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ivno - Build with Gradle
        run: ../gradlew build --stacktrace --info --build-cache
        working-directory: ivno
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #      - name: Ivno - Compile deposit-request circuit with Zargo
      #        run: zargo build -v
      #        working-directory: ivno/ivno-collateral-token-contract/build/zinc/deposit-request
      #        env:
      #          GITHUB_USERNAME: ${{ github.actor }}
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JUnit test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Junit Test Report
          path: build/reports/tests/test

      - name: Upload OWASP report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: OWASP Dependency Check Report
          path: build/reports/dependency-check-report.html

      - name: Upload detekt report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Detekt Report
          path: build/reports/detekt
