name: All checks nightly

on:
  schedule:
    # Run nightly at 04:00, so we don't use up our run hours too fast
    - cron:  '0 4 * * *'

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8.0.x (FX)
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.x
          java-package: jdk+fx

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-1
          restore-keys: ${{ runner.os }}-gradle

      - name: Fetch Zinc ING Fork
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "ingzkp/zinc"
          version: "latest"
          file: "zinc-linux.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Zinc ING Fork and add to $PATH
        run: |
          tar xvzf zinc-linux.tar.gz
          echo "$GITHUB_WORKSPACE/zinc-linux/" >> $GITHUB_PATH

      - name: Build with Gradle
        run: ./gradlew assemble --build-cache --stacktrace --parallel
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  all-tests:
    runs-on: ubuntu-latest
    needs: assemble

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8.0.x (FX)
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.x
          java-package: jdk+fx

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-1
          restore-keys: ${{ runner.os }}-gradle

      - name: Fetch Zinc ING Fork
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "ingzkp/zinc"
          version: "latest"
          file: "zinc-linux.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Zinc ING Fork and add to $PATH
        run: |
          tar xvzf zinc-linux.tar.gz
          echo "$GITHUB_WORKSPACE/zinc-linux/" >> $GITHUB_PATH

      - name: Build with Gradle
        run: ./gradlew check slowTest --stacktrace --info
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Junit Test Report - Notary - Fast tests
          path: notary/build/reports/tests/test

      - name: Upload slow test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Junit Test Report - Notary - Fast tests
          path: notary/build/reports/tests/slowTest

      - name: Upload detekt report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Detekt Report - Notary
          path: notary/build/reports/detekt
